services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: pricehawk-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: pricehawk-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
